add_library(eacp-network STATIC)

target_sources(eacp-network PRIVATE
        HTTP/Http.cpp
        HTTP/HttpAsync.cpp
        HTTP/HttpProtocol.cpp
        HTTPServer/HttpServer.cpp
        HTTPServer/HttpServerDispatcher.cpp
        HTTPServer/ResponseBuilders.cpp
        IPC/Channel.cpp
        IPC/Lock.cpp
        IPC/Messenger.cpp
        IPC/Names.cpp
        OnlineResource/OnlineResource.cpp
        OnlineResource/OnlineResources.cpp
        TCP/Connection.cpp
        TCP/Listener.cpp
        WebSocket/Protocol.cpp
        WebSocket/Server.cpp
        WebSocket/WebSocket.cpp)

target_link_libraries(eacp-network PUBLIC eacp-core)

if (APPLE)
    target_sources(eacp-network PRIVATE
            HTTP/Http.mm
            HTTPServer/HttpServer.mm
            IPC/Channel-Apple.cpp
            IPC/Channel-Posix.cpp
            IPC/Lock-Posix.cpp
            TCP/Connection-Posix.cpp
            WebSocket/WebSocket.mm)
    target_link_libraries(eacp-network PRIVATE
            "-framework Foundation"
            "-framework CoreFoundation"
            "-framework Network")
elseif (WIN32)
    target_sources(eacp-network PRIVATE
            HTTP/Http-Windows.cpp
            HTTPServer/HttpServer-Windows.cpp
            IPC/Channel-Windows.cpp
            IPC/Lock-Windows.cpp
            TCP/Connection-Windows.cpp
            WebSocket/WebSocket-Windows.cpp)
    target_link_libraries(eacp-network PRIVATE winhttp ws2_32 advapi32)
elseif (ANDROID)
    target_sources(eacp-network PRIVATE
            HTTP/Http-Android.cpp
            HTTPServer/HttpServer-Linux.cpp
            IPC/Channel-Linux.cpp
            IPC/Channel-Posix.cpp
            IPC/Lock-Posix.cpp
            TCP/Connection-Posix.cpp
            WebSocket/WebSocket-Android.cpp)
elseif (UNIX AND NOT APPLE)
    target_sources(eacp-network PRIVATE
            HTTP/Http-Linux.cpp
            HTTPServer/HttpServer-Linux.cpp
            IPC/Channel-Linux.cpp
            IPC/Channel-Posix.cpp
            IPC/Lock-Posix.cpp
            TCP/Connection-Posix.cpp
            WebSocket/WebSocket-Linux.cpp)
    find_package(CURL ${EACP_FIND_QUIET} REQUIRED)
    target_link_libraries(eacp-network PRIVATE CURL::libcurl)
endif ()

set_default_target_setting(eacp-network)
eacp_enable_unity_build(eacp-network)
add_ide_sources(eacp-network)

find_package(Miro REQUIRED)

add_library(eacp-network-json STATIC)

target_sources(eacp-network-json PRIVATE
        HTTPServer/Json.cpp)

target_link_libraries(eacp-network-json PUBLIC eacp-network Miro)

set_default_target_setting(eacp-network-json)
eacp_enable_unity_build(eacp-network-json)
add_ide_sources(eacp-network-json)

add_library(eacp-network-rpc STATIC)

target_sources(eacp-network-rpc PRIVATE
        HTTPRpc/RpcServer.cpp
        HTTPRpc/RpcClient.cpp
        IPCRpc/RpcServer.cpp
        IPCRpc/RpcClient.cpp
        Rpc/AsyncCommand.cpp)

target_link_libraries(eacp-network-rpc PUBLIC eacp-network Miro)

set_default_target_setting(eacp-network-rpc)
eacp_enable_unity_build(eacp-network-rpc)
add_ide_sources(eacp-network-rpc)
