# eacp_add_run_harness(<target>) — generates a debugger-wrapped
# launcher for an executable target at a predictable path:
#
#     <build>/run/<Target>          (single-config generators)
#     <build>/run/<Config>/<Target> (multi-config generators)
#
# The launcher behaves like running the binary directly — arguments,
# environment, stdout/stderr all pass through, so workflows like the
# MCP debug server are unaffected — but the process runs under a
# batch-mode debugger: a crash prints a full backtrace and exits
# non-zero instead of dying silently. This is the launcher humans, CI,
# and coding agents should reach for by default.
#
# Debugger selection happens at launch, not configure: lldb, then gdb,
# then a plain exec on POSIX; cdb (Debugging Tools for Windows), then a
# plain start on Windows. Set EACP_NO_DEBUGGER=1 to bypass the debugger
# without changing the call site.
#
# eacp_add_webview_app() calls this automatically for every app it
# creates; call it directly for hand-rolled executable targets:
#
#     add_executable(MyTool Main.cpp)
#     eacp_add_run_harness(MyTool)
#
# Also defines a `run-<Target>` convenience target (build + launch):
#     cmake --build build --target run-MyTool

function(eacp_add_run_harness TARGET)
    if (NOT TARGET ${TARGET})
        message(FATAL_ERROR "eacp_add_run_harness(${TARGET}): no such target")
    endif ()

    get_target_property(TARGET_TYPE ${TARGET} TYPE)
    if (NOT TARGET_TYPE STREQUAL "EXECUTABLE")
        message(FATAL_ERROR
                "eacp_add_run_harness(${TARGET}): target is ${TARGET_TYPE}, "
                "expected EXECUTABLE")
    endif ()

    # Multi-config generators resolve $<TARGET_FILE> differently per
    # config, so each config gets its own script directory.
    if (CMAKE_CONFIGURATION_TYPES)
        set(RUN_DIR "${CMAKE_BINARY_DIR}/run/$<CONFIG>")
    else ()
        set(RUN_DIR "${CMAKE_BINARY_DIR}/run")
    endif ()

    if (WIN32)
        set(SCRIPT_PATH "${RUN_DIR}/${TARGET}.cmd")
        set(CONTENT "@echo off
rem Generated by eacp_add_run_harness(${TARGET}) - do not edit.
rem Runs the app under cdb when available so a crash prints stacks.
rem Set EACP_NO_DEBUGGER=1 to launch the binary directly.
set \"BINARY=$<TARGET_FILE:${TARGET}>\"

if defined EACP_NO_DEBUGGER goto direct

where cdb >nul 2>nul
if not %ERRORLEVEL%==0 goto direct

rem -g/-G skip the initial/final breakpoints, so the -c command only
rem runs when an exception stops the process: print stacks and quit.
cdb -g -G -c \"!uniqstack -p; q\" \"%BINARY%\" %*
exit /b %ERRORLEVEL%

:direct
\"%BINARY%\" %*
exit /b %ERRORLEVEL%
")
    else ()
        set(SCRIPT_PATH "${RUN_DIR}/${TARGET}")
        set(CONTENT "#!/bin/sh
# Generated by eacp_add_run_harness(${TARGET}) - do not edit.
# Runs the app under a batch-mode debugger: behaves like a plain
# launch (args, env, stdio pass through), but a crash prints a full
# backtrace and exits non-zero. Set EACP_NO_DEBUGGER=1 to launch the
# binary directly.
BINARY=\"$<TARGET_FILE:${TARGET}>\"

if [ -n \"$EACP_NO_DEBUGGER\" ]; then
    exec \"$BINARY\" \"$@\"
fi

if command -v lldb >/dev/null 2>&1; then
    exec lldb --batch -o run \\
        -k \"thread backtrace all\" -k \"quit 1\" -- \"$BINARY\" \"$@\"
fi

if command -v gdb >/dev/null 2>&1; then
    exec gdb --batch -ex run -ex \"thread apply all bt\" \\
        --args \"$BINARY\" \"$@\"
fi

exec \"$BINARY\" \"$@\"
")
    endif ()

    file(GENERATE
            OUTPUT "${SCRIPT_PATH}"
            CONTENT "${CONTENT}"
            TARGET ${TARGET}
            FILE_PERMISSIONS
                OWNER_READ OWNER_WRITE OWNER_EXECUTE
                GROUP_READ GROUP_EXECUTE
                WORLD_READ WORLD_EXECUTE)

    if (NOT TARGET run-${TARGET})
        add_custom_target(run-${TARGET}
                COMMAND "${SCRIPT_PATH}"
                DEPENDS ${TARGET}
                USES_TERMINAL
                COMMENT "Running ${TARGET} under the debug harness")

        # Group next to the target it runs in IDE target trees.
        get_target_property(TARGET_FOLDER ${TARGET} FOLDER)
        if (TARGET_FOLDER)
            set_target_properties(run-${TARGET} PROPERTIES
                    FOLDER "${TARGET_FOLDER}")
        endif ()
    endif ()
endfunction()
