include(CPM)

# find_package rather than include(FindPkgConfig): this file is itself
# reached through find_package(VulkanBackend), and a bare include leaves
# PkgConfig's find_package_handle_standard_args reporting against the wrong
# package name.
find_package(PkgConfig REQUIRED)

# Nothing links libvulkan: volkInitialize() dlopens it at runtime. Vulkan-Headers
# and volk must share one SDK tag - volk's table is generated per header revision.

set(EACP_VULKAN_SDK_TAG vulkan-sdk-1.4.313.0)
set(EACP_VMA_TAG v3.4.0)

function(eacp_fetch_vulkan_sources)
    CPMAddPackage(
            NAME VulkanHeaders
            GITHUB_REPOSITORY KhronosGroup/Vulkan-Headers
            GIT_TAG ${EACP_VULKAN_SDK_TAG}
            GIT_SHALLOW YES
            DOWNLOAD_ONLY YES
            SYSTEM YES
            ${EACP_FETCH_QUIET})

    CPMAddPackage(
            NAME volk
            GITHUB_REPOSITORY zeux/volk
            GIT_TAG ${EACP_VULKAN_SDK_TAG}
            GIT_SHALLOW YES
            DOWNLOAD_ONLY YES
            SYSTEM YES
            ${EACP_FETCH_QUIET})

    CPMAddPackage(
            NAME VulkanMemoryAllocator
            GITHUB_REPOSITORY GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator
            GIT_TAG ${EACP_VMA_TAG}
            GIT_SHALLOW YES
            DOWNLOAD_ONLY YES
            SYSTEM YES
            ${EACP_FETCH_QUIET})

    set(VulkanHeaders_SOURCE_DIR "${VulkanHeaders_SOURCE_DIR}" PARENT_SCOPE)
    set(volk_SOURCE_DIR "${volk_SOURCE_DIR}" PARENT_SCOPE)
    set(VulkanMemoryAllocator_SOURCE_DIR
            "${VulkanMemoryAllocator_SOURCE_DIR}" PARENT_SCOPE)
endfunction()

if (NOT TARGET eacp-vulkan)
    eacp_fetch_vulkan_sources()

    file(CONFIGURE
            OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/eacp-vma.cpp"
            CONTENT [[
// Generated by CMake/FindVulkanBackend.cmake. volk.h first, so the declarations
// VMA finds are the function-pointer ones.
#include <volk.h>

#define VMA_IMPLEMENTATION
#include <vk_mem_alloc.h>
]]
            @ONLY)

    add_library(eacp-vulkan STATIC
            "${volk_SOURCE_DIR}/volk.c"
            "${CMAKE_CURRENT_BINARY_DIR}/eacp-vma.cpp")

    target_include_directories(eacp-vulkan SYSTEM PUBLIC
            "${VulkanHeaders_SOURCE_DIR}/include"
            "${volk_SOURCE_DIR}"
            "${VulkanMemoryAllocator_SOURCE_DIR}/include")

    # PUBLIC: volk.c must see the platform defines too, or
    # vkCreateWaylandSurfaceKHR and vkCreateXcbSurfaceKHR are missing from the
    # dispatch table.
    target_compile_definitions(eacp-vulkan PUBLIC
            VK_NO_PROTOTYPES
            VK_USE_PLATFORM_WAYLAND_KHR
            VK_USE_PLATFORM_XCB_KHR
            VMA_STATIC_VULKAN_FUNCTIONS=0
            VMA_DYNAMIC_VULKAN_FUNCTIONS=1
            VMA_VULKAN_VERSION=1003000)

    # vulkan_xcb.h includes <xcb/xcb.h>, so every consumer of the headers needs
    # to be able to find it. The headers only: nothing here links xcb.
    pkg_check_modules(EACP_VULKAN_XCB xcb)

    if (EACP_VULKAN_XCB_FOUND)
        target_include_directories(eacp-vulkan SYSTEM PUBLIC
                ${EACP_VULKAN_XCB_INCLUDE_DIRS})
    endif ()

    # The loader is opened by name at runtime; only the opener is linked.
    target_link_libraries(eacp-vulkan PUBLIC ${CMAKE_DL_LIBS})

    # Third-party headers, not clean under eacp's warning set.
    target_compile_options(eacp-vulkan PRIVATE
            $<$<CXX_COMPILER_ID:GNU,Clang>:-w>)

    set_target_properties(eacp-vulkan PROPERTIES
            POSITION_INDEPENDENT_CODE ON
            FOLDER "${CMAKE_FOLDER}")
endif ()
